### ISSUE TITLE
Overview of client tasks

### ISSUE THREAD

**Issue by vidvidvid** [People-s/peoples-app#4]
### Header

- [x] logo
- [x] search input
- [x] dark mode
- [x] profile popover
- [x] settings ?
- [x] log out button

### Dashboard

- [x] channels
  - [x] avatar + name
- [x] join or create a channel
  - [x] join form
  - [x] create form
- [x] currently online
  - [x] avatar
  - [x] name
  - [x] address

### Functionality
- [x] dark mode
- [ ] search input - search for groups
- [ ] add stuff to profile popover 
  - [ ] profile page
  - [ ] history?
- [ ] log out / sign in button 

### To-Do
- [x] change react icon in tab
- [x] change name of app in tab
- [x] fix light/dark mode landing page animation color
